### ISSUE TITLE
Issue instaling cnvkit 0.9.7

### ISSUE THREAD

**Issue by SouzaBB** [etal/cnvkit#477]
I'm trying to install cnvkit 0.9.7 on a CentOS 7 server and, after following all recommended steps for installing from source, I'm getting the following error:

`Traceback (most recent call last):
  File "/usr/bin/cnvkit.py", line 8, in <module>
    execfile(__file__)
  File "/home/idengene/CNV/bin/cnvkit/cnvkit.py", line 4, in <module>
    from cnvlib import commands
  File "/home/idengene/CNV/bin/cnvkit/cnvlib/__init__.py", line 1, in <module>
    from skgenome.tabio import write
  File "/home/idengene/CNV/bin/cnvkit/skgenome/__init__.py", line 1, in <module>
    from . import tabio
  File "/home/idengene/CNV/bin/cnvkit/skgenome/tabio/__init__.py", line 14, in <module>
    from . import (bedio, genepred, gff, picard, seg, seqdict, tab, textcoord, vcfio,
  File "/home/idengene/CNV/bin/cnvkit/skgenome/tabio/seg.py", line 22, in <module>
    from itertools import zip_longest
ImportError: cannot import name zip_longest
`
Does anyone know what can be happening? Need to install any other dependencies??

Thanks

**Comment by SouzaBB** [comment]
The issue was resolved downgrading to v0.9.6

**Comment by etal** [comment]
CNVkit 0.9.7 only works on Python 3, so v0.9.6 is the last release that will work on Python 2.
